version: '3.8'
services:
  webserver:
    build: ./build/webserver/
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
      - ./config/php:/usr/local/etc/php/
      - ./config/apache:/etc/apache2/sites-enabled
    depends_on:
      - db
    #command: >
    #  bash -c "wget https://www.shopware.com/de/Download/redirect/version/sw6/file/install_v6.3.0.2_b5788541058257e6114b7405a41a36946132af9c.zip -q -O shopware.zip
    #    unzip -q shopware.zip 
    #    rm shopware.zip"

  db:
    #image: mysql/mysql-server
    build: ./build/database/
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: shopware
      MYSQL_DATABASE: shopware
      MYSQL_USER: shopware
      MYSQL_PASSWORD: shopware   
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db